# Generated by Django 4.1.1 on 2022-10-03 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(db_column='ID_Genero', primary_key=True, serialize=False)),
                ('genero', models.CharField(db_column='Genero', max_length=45)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.IntegerField(db_column='ID_Pelicula', primary_key=True, serialize=False)),
                ('nombre_pelicula', models.CharField(db_column='Nombre_Pelicula', max_length=50)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=500)),
                ('director', models.CharField(db_column='Director', max_length=45)),
                ('duracion', models.CharField(db_column='Duracion', max_length=45)),
            ],
            options={
                'db_table': 'pelicula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
                ('apellido', models.CharField(db_column='Apellido', max_length=45)),
                ('telefono', models.IntegerField(db_column='Telefono')),
                ('correo', models.CharField(db_column='Correo', max_length=50)),
                ('rol', models.CharField(db_column='Rol', max_length=45)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=45)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaHasGenero',
            fields=[
                ('pelicula_id_pelicula', models.OneToOneField(db_column='Pelicula_ID_Pelicula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='index.pelicula')),
            ],
            options={
                'db_table': 'pelicula_has_genero',
                'managed': False,
            },
        ),
    ]
